Preface

cell no.: content
2: How to create tensor
3: Getting info. about tensor variable
4: Creating random tensor
5: torch.zeros_like
6: torch.tensor's parameter
7: View,Stacking,Squeeze,Unsqueeze,permute
8: torch.from_numpy
9: torch.manual_seed
10: Moving tensor to gpu

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# How to create tensor
TENSOR = torch.tensor(7) # tensor, matrix in upper case
TENSOR

tensor(7)

In [3]:
# Getting info. about tensor variable
TENSOR.ndim # see dimension
TENSOR.item() # see item
TENSOR.shape # see shpae

torch.Size([])

In [4]:
# Creating random tensor
random_tensor = torch.rand(3,4,3)
random_tensor

tensor([[[0.7668, 0.3529, 0.7377],
         [0.4507, 0.1317, 0.1663],
         [0.7363, 0.9104, 0.4573],
         [0.7312, 0.6613, 0.5289]],

        [[0.3842, 0.4830, 0.5679],
         [0.7411, 0.3047, 0.4357],
         [0.0113, 0.3062, 0.2606],
         [0.8682, 0.3294, 0.4889]],

        [[0.5340, 0.4373, 0.0345],
         [0.4382, 0.3475, 0.9767],
         [0.8153, 0.3521, 0.9079],
         [0.5933, 0.1766, 0.8703]]])

In [5]:
# tensor.zeros_like
base = torch.empty(3,2)
torch.zeros_like(base) # We want a zero matrix size like(this tensor)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [6]:
float32_tensor = torch.tensor([2.0,3.0,4.0],
             dtype = None, # Even though none but the default is float32
             device = "cpu",
             requires_grad= False) # enable torch to track the gradient of thsi
                                  #tensor when going through numerical operation


In [7]:
# A view of a tensor shares the same memory changing one changes both
x = torch.arange(1,10)
z = x.view(3,3) # like reshaping
#print(z)
#print(x)
# Changing either will change both
x[0] = 999
#print(z)

# Stack
x_stacked = torch.stack([x,x], dim = 0) # 0: vertical, 1: horizontal

# Squeeze and Unsqeeze
tensor_for_squeeze = torch.rand(2,3,1,1)
squeeze_tensor = tensor_for_squeeze.squeeze()# Removes all dim of input
                                             # size 1
# print(squeeze_tensor.shape)
one_dim_on_left = tensor_for_squeeze.unsqueeze(dim = 0) # Add 1D on left
one_dim_on_right = tensor_for_squeeze.unsqueeze(dim = 1) # Add 1D on right

# Permute returns a view of the original tensor with its dim permuted
#                   ^^^^^^^ changing one changes other
tensor_for_permute = torch.rand(1,2,3)
tensor_permuted = tensor_for_permute.permute(2,0,1)# These are index of dim
tensor_permuted.shape

torch.Size([3, 1, 2])

In [8]:
# torch.from_numpy to convert numpy array into tensor
array_to_convert = np.array([3.0,4.0,5.0])
array_converted = torch.from_numpy(array_to_convert)
print(array_converted.dtype) # array's default dtype is float64(careful!)

# To convert back into array
converted_back = array_converted.numpy()

torch.float64


In [11]:
torch.manual_seed(42)
a = torch.rand(2,3)

# torch.manual_seed(42)
b = torch.rand(2,3)

print(a == b) # False

# In torch we need use seed every time we create a tensor

tensor([[False, False, False],
        [False, False, False]])


In [19]:
# We could write a gpu run tensor by device = 'cuda' but better way in colab is

device = 'cuda' if torch.cuda.is_available() else 'cpu'

x = torch.tensor([1,2,3]) # Default device = cpu
x_to_gpu = x.to(device) # Assifn gpu if available in colab
print(x_to_gpu.device)

# Device error(Can't convert gpu based tensor into array)
x_to_gpu.numpy() # Error if gpu is available
x_to_gpu.cpu().numpy() # Convert into cpu then numpy

cpu


array([1, 2, 3])